// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppPlusPlus.Infrastructure.Persistence;

#nullable disable

namespace AppPlusPlus.Infrastructure.Migrations.GRH
{
    [DbContext(typeof(GrhDbContext))]
    partial class GrhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Toutes les entités GRH sont configurées ici
            // Les configurations sont appliquées via ApplyConfigurationsFromAssembly

#pragma warning restore 612, 618
        }
    }
}
